version: "3.8"
services:
  portfolio-site:
    container_name: portfolio-site
    image: portfolio-site:latest
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/landaverde.in:/etc/letsencrypt/live/landaverde.in:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true