spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

server:
  port: 8080
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/landaverde.in/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
